version: "3"

services:
    web-ui:
        build: .
        container_name: "dentalia-profile-ui"
        restart: "always"
        ports:
            - "8081:80"
        volumes:
            - "./dist/:/usr/share/nginx/html"